// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB_YzF95vujSq4yLkdWpDLKuXiP8YIUE8',
    appId: '1:1084778978204:web:985ab7d920200d3d158659',
    messagingSenderId: '1084778978204',
    projectId: 'banquetbookz-4a22d',
    authDomain: 'banquetbookz-4a22d.firebaseapp.com',
    databaseURL: 'https://banquetbookz-4a22d-default-rtdb.firebaseio.com',
    storageBucket: 'banquetbookz-4a22d.firebasestorage.app',
    measurementId: 'G-S31GM4GHXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCElnrkpwjjPmPXqeewcBUUzRPXoT2o_GA',
    appId: '1:1084778978204:android:8b04c292277da6d1158659',
    messagingSenderId: '1084778978204',
    projectId: 'banquetbookz-4a22d',
    databaseURL: 'https://banquetbookz-4a22d-default-rtdb.firebaseio.com',
    storageBucket: 'banquetbookz-4a22d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-o0V6xsinvvLp_9mbAzs-gxJFVH1pJLk',
    appId: '1:1084778978204:ios:a15a32a21b42f0e0158659',
    messagingSenderId: '1084778978204',
    projectId: 'banquetbookz-4a22d',
    databaseURL: 'https://banquetbookz-4a22d-default-rtdb.firebaseio.com',
    storageBucket: 'banquetbookz-4a22d.firebasestorage.app',
    iosBundleId: 'com.example.bbVendor',
  );
}
